### ISSUE TITLE
FreeBSD 11, python 3.6.0 - examle silently doesn't work (always not started)

### ISSUE THREAD

**Issue by Savier** [ImmobilienScout24/succubus#5]
I think succubus don't compatible with python3 (I saw at least file()), but it is difficult to understand without any diagnostics.

**Comment by Savier** [comment]
Oops, sorry, changing file() to open() seems resolve issue

**Comment by snordhausen** [comment]
You are right, Python 3 was not working.

I committed 4c854006866af592641c39720048abe422d7b41c which makes the integration tests run with the correct Python version, thus exposing the bug. Interestingly, this worked on my computer but not on TravisCI.

I committed 392a87c11d3341cc8409b13b7722759809c8992f to fix the issue. Still, I would like to configure the build so that TravisCI runs the tests with the correct Python version, so not closing this ticket.

**Comment by snordhausen** [comment]
Turns out I deactivated integration tests on TravisCI myself: 4479de2a3e4afd816154663ff1c2d8a8b4f0757f I reactivated the tests, which exposed two other bugs with Pypy, which are also fixed now.

In summary, integration tests now use the correct Python interpreter and run successfully on TravisCI with Python 2, Python 3 and Pypy.
